### ISSUE TITLE
unable to make light/dark mode toggle for stories. unable to use new storybook since it is using "type": "commonjs"

### ISSUE THREAD

**Issue by Jared-Dahlke** [moishinetzer/pbandj-withtailwind#1]
hey there, i'm having to use the 7.0.0.beta version of storybook in this example. If i try to update storybook i cannot , and based off research i think it's because you are using "type": "commonjs" in package.json.

The reason this is a problem is i am unable to implement a light/dark mode in this older storybook version. The ones available that I've figured out are only for the newer versions of 7.

This will be something necessary for the shadcn integration

**Comment by moishinetzer** [comment]
Hi I don't plan on integrating shadcn into this repo. Please provide a working reproduction of your issue with clear instructions and or screenshots.

**Comment by Jared-Dahlke** [comment]
@moishinetzer I was able to use "type":"module" in the package.json , change `postcss.config.js` to `postcss.config.cjs` and change `tailwind.config.js` to `tailwind.config.cjs` , which let me successfully upgrade to storybook 7.4.

I've tried to implement dark mode toggle in storybook but it is not working. I think it might have to do with how we are injecting styling, because it works in my tsdx version of this library.

I understand if this is out of your concern, but would appreciate it if you could give it a glance and let me know why light/dark mode toggle in storybook doesn't seem to be working. The configuration in there is the same configuration that works in my tsdx version of this library.


Here is the repo:
https://github.com/Jared-Dahlke/pbj4

**Comment by Jared-Dahlke** [comment]
@moishinetzer I figured out why the dark/light mode toggle didn't work. I didn't have my theme providers in the library yet.

ps. I ended up going with a different configuration that enables file by file code splitting. here is what the package.json looks like:

```
types": "dist/index.d.ts",
  "style": "dist/tailwind.css",
  "main": "dist/src/index.js",
  "exports": {
    ".": {
      "import": "./dist/src/index.esm.js",
      "types": "./dist/index.d.ts",
      "require": "./dist/src/index.cjs.js"
    },
    "./Button": {
      "import": "./dist/src/components/ui/button.esm.js",
      "types": "./dist/src/components/ui/button.d.ts",
      "require": "./dist/src/components/ui/button.cjs.js"
    },
    "./Headings": {
      "import": "./dist/src/Headings.esm.js",
      "types": "./dist/Headings.d.ts",
      "require": "./dist/src/Headings.cjs.js"
    },
    "./Icons": {
      "import": "./dist/src/Icons.esm.js",
      "types": "./dist/Icons.d.ts",
      "require": "./dist/src/Icons.cjs.js"
    },
    "./styles.css": {
      "import": "./dist/style.css",
      "require": "./dist/style.css"
    }

```
